name: Build docker image

on:
  push:
    branches:
    - opensearch-dashboards
    - opensearch-dashboards-1.x

    tags:
    - '*'

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dashboards-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '1.3.17'
        tags: 1.3.17,1.3,2
