name: Build docker image

on:
  push:
    branches:
    - opensearch-dashboards

    tags:
    - '*'

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dashboards-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '2.12.0'
        tags: 2.12.0,2.12,2,latest
